// File generated by Antigravity AI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2Zfou_qWE-0wD3nCddUWDNx1zkfS6pk',
    appId: '1:275549574877:web:8c5123d517c52dbf282d34',
    messagingSenderId: '275549574877',
    projectId: 'movie-booking-app-da3b3',
    authDomain: 'movie-booking-app-da3b3.firebaseapp.com',
    storageBucket: 'movie-booking-app-da3b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2Zfou_qWE-0wD3nCddUWDNx1zkfS6pk',
    appId: '1:275549574877:android:88248b67167d0695282d34',
    messagingSenderId: '275549574877',
    projectId: 'movie-booking-app-da3b3',
    storageBucket: 'movie-booking-app-da3b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2Zfou_qWE-0wD3nCddUWDNx1zkfS6pk',
    appId: '1:275549574877:ios:88248b67167d0695282d34',
    messagingSenderId: '275549574877',
    projectId: 'movie-booking-app-da3b3',
    storageBucket: 'movie-booking-app-da3b3.firebasestorage.app',
    iosBundleId: 'com.movieapp.flutter_app',
  );
}
